# SPDX-License-Identifier: 0BSD
name: gosec
on:
  push:
    paths:
      - '**/*.go'
      - '**/go.mod'
      - '**/go.sum'
      - '**/Makefile'
      - 'Makefile'
      - '.github/workflows/gosec.yml'
  pull_request:
    paths:
      - '**/*.go'
      - '**/go.mod'
      - '**/go.sum'
      - '**/Makefile'
      - 'Makefile'
      - '.github/workflows/gosec.yml'

permissions:
  contents: read

jobs:
  gosec:
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: stable

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec
        run: make gosec
