# SPDX-License-Identifier: 0BSD
name: gosec
on:
  push:
    paths:
      - '**/*.go'
      - '**/go.mod'
      - '**/go.sum'
      - '**/Makefile'
      - 'Makefile'
      - '.github/workflows/gosec.yml'
  pull_request:
    paths:
      - '**/*.go'
      - '**/go.mod'
      - '**/go.sum'
      - '**/Makefile'
      - 'Makefile'
      - '.github/workflows/gosec.yml'

permissions:
  contents: read

jobs:
  gosec:
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: stable

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec
        run: make gosec
